eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: app-login
  redis:
    database: 0
    ssl: false
    pool:
      maxTotal: 10
      maxWaitMillis: 3000
    host: 192.168.100.161
    port: 6379

server:
  port: 18762
